### ISSUE TITLE
Release version with support for ES 1.2.4

### ISSUE THREAD

**Issue by bearrito** [tomcashman/metrics-elasticsearch#1]
The version on maven.org seems out of date in comparison to master. Any chance this might be updated?

Thank you.

**Comment by tomcashman** [comment]
I've never deployed to maven.org, that's the metrics reporter by the Elasticsearch team which only works over HTTP.

However, I noticed that my maven repo is down. I'll work on getting it back online this evening and update the documentation. Once that's done I'll get the library updated to work with newer versions of Elasticsearch.

Thanks for the using the library! :)

**Comment by bearrito** [comment]
Thank you very much.

**Comment by tomcashman** [comment]
The maven repo is back up, please refer to the [wiki](https://github.com/tomcashman/metrics-elasticsearch/wiki) for more details on how to add the repo to your Maven/Gradle builds.

I've also updated the library to work with Elasticsearch 1.3.9. Please refer to the [version compatibility page](https://github.com/tomcashman/metrics-elasticsearch/wiki/Compatibility) for more info.

There's an issue with getting it to work with 1.4.4 which I'm investigating.

**Comment by bearrito** [comment]
On my end it looks like the repo is returning a 404.

**Comment by tomcashman** [comment]
Not on my end? You're using this URL? -> http://viridiansoftware.com/maven/content/repositories/releases/

**Comment by bearrito** [comment]
It was returning a 404 then I checked again later in the evening and was working fine. Looks good on my end now. Thank you.

**Comment by tomcashman** [comment]
No problem :)
